// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/whatsapp/ChatsList.tsx": () => import("../components/mockups/whatsapp/ChatsList.tsx"),
  "./components/mockups/whatsapp/Conversation.tsx": () => import("../components/mockups/whatsapp/Conversation.tsx"),
  "./components/mockups/whatsapp/LinkedDevices.tsx": () => import("../components/mockups/whatsapp/LinkedDevices.tsx")
};
